#!/bin/bash

if [ $# -ne 1 ]
then
    echo "Usage: Enter the target container name"
    exit 1
fi

target_con=$1

#create main 4 directories
sudo lxc exec $target_con -- mkdir -p /root/Research_Data /root/Project_Source_Files /root/Grant_Proposals /root/Staff_Information

#create the files within those directories
sudo lxc exec $target_con -- bash -c 'touch /root/Research_Data/Machine_Learning_Datasets /root/Research_Data/Cybersecurity_Logs /root/Research_Data/Algorithm_Benchmarks.exe /root/Research_Data/User_Study_Results'

sudo lxc exec $target_con -- bash -c 'touch /root/Project_Source_Files/Senior_Capstone_Code.java /root/Project_Source_Files/AI_Research_Code.py /root/Project_Source_Files/Robotics_Simulation_Code.c /root/Project_Source_Files/Web_Development_Projects'

sudo lxc exec $target_con -- bash -c 'touch /root/Grant_Proposals/NSF_Grant_Proposal_2025 /root/Grant_Proposals/Cybersecurity_Innovation_Proposal /root/Grant_Proposals/Robotics_Innovation_Grant /root/Grant_Proposals/AI_for_Education_Proposal'

sudo lxc exec $target_con -- bash -c 'touch /root/Staff_Information/Staff_Identification_Number /root/Staff_Information/Social_Security_Number /root/Staff_Information/Address /root/Staff_Information/Tax_Forms'

sudo lxc exec $target_con -- chmod u+x /root/Project_Source_Files/Senior_Capstone_Code.java /root/Project_Source_Files/AI_Research_Code.py /root/Project_Source_Files/Robotics_Simulation_Code.c
#hide the snap directory
sudo lxc exec $target_con -- mv /root/snap /root/.snap
