#!/bin/bash

sudo screen -S "server1_mainloop" -X quit
sudo screen -S "server2_mainloop" -X quit
sudo screen -S "server3_mainloop" -X quit
sudo screen -S "server4_mainloop" -X quit

sudo screen -S "timer_server1" -X quit
sudo screen -S "timer_server2" -X quit
sudo screen -S "timer_server3" -X quit
sudo screen -S "timer_server4" -X quit

sudo screen -S "idle_server1" -X quit
sudo screen -S "idle_server2" -X quit
sudo screen -S "idle_server3" -X quit
sudo screen -S "idle_server4" -X quit

/home/aces/Bumblebees/deletion_script server1
/home/aces/Bumblebees/deletion_script server2
/home/aces/Bumblebees/deletion_script server3
/home/aces/Bumblebees/deletion_script server4
