#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: ./deletion_script <container name>"
  exit 1
fi

containerName=$1

sudo screen -S "mitm_${containerName}" -X quit

sudo lxc stop "$containerName"
sudo lxc delete "$containerName"
