#!/bin/bash

if [ $# -ne 3 ]
then
  echo "Usage: ./deletion_script <external IP> <MITM port> <container name>"
  exit 1
fi

extIP=$1
mitm_port=$2
containerName=$3

intIP=$(sudo lxc exec "$containerName" -- hostname -I)

sudo screen -S process_name -X quit


sudo lxc exec "$containerName" -- systemctl stop ssh || sudo lxc exec "$containerName" -- service ssh stop
sudo lxc stop "$containerName"
sudo lxc delete "$containerName"

