#!/bin/bash

sudo screen -dmS server1_mainloop /home/aces/Bumblebees/main_loop_new 02 server1
sudo screen -dmS server2_mainloop /home/aces/Bumblebees/main_loop_new 03 server2
sudo screen -dmS server3_mainloop /home/aces/Bumblebees/main_loop_new 04 server3
sudo screen -dmS server4_mainloop /home/aces/Bumblebees/main_loop_new 05 server4


