#!/bin/bash

num_server1=$(sudo cat /home/aces/Bumblebees/honeypot_activity.log | grep "attacker is inside" | grep "server1" | wc -l)
num_server2=$(sudo cat /home/aces/Bumblebees/honeypot_activity.log | grep "attacker is inside" | grep "server2" | wc -l)
num_server3=$(sudo cat /home/aces/Bumblebees/honeypot_activity.log | grep "attacker is inside" | grep "server3" | wc -l)
num_server4=$(sudo cat /home/aces/Bumblebees/honeypot_activity.log | grep "attacker is inside" | grep "server4" | wc -l)

echo 
echo "$num_server1 attacks on server1"
echo "$num_server2 attacks on server2"
echo "$num_server3 attacks on server3"
echo "$num_server4 attacks on server4"

truncate -s 0 /home/aces/Bumblebees/honeypot_activity.log
