#!/bin/bash

if [ $# -ne 2 ]
then
  echo "Usage: profile container_name"
  exit 1
fi

profile=$1
con_name=$2
auth_log=/root/containers/${con_name}/rootfs/var/log/auth.log

while true
do
  num=$(python3 -c "import random; print(random.randint(1,3))")
  echo config num is $num
  timestamp="$(date +%s)"
  ./creation $con_name $profile $num $timestamp
  data_collection="/home/aces/Bumblebees/Attacker_Data/${con_name}_${timestamp}.txt"

  # stream only new lines; check both connect and disconnect in same loop
  sudo tail -n0 -F ${auth_log} | while read -r LINE
  do
      if echo "$LINE" | grep -q "Accepted password"
      then
        echo "attacker is inside"
        sudo screen -dmS timer_${con_name} /home/aces/Bumblebees/time_attacker $con_name $timestamp
        #sudo screen -dmS idle_${con_name} /home/aces/Bumblebees/idle_time $con_name 2m $timestamp

      fi

      if echo "$LINE" | grep -q "Disconnected from user" || echo "$LINE" | grep -q "Attacker timed out"; then

          # kill the tail process streaming that specific auth_log
          sudo pkill -f "tail -n0 -F ${auth_log}" || true
          sudo screen -S "timer_${con_name}" -X quit
          echo "$(date +"%Y-%m-%d %H:%M:%S.%3N")" > "$data_collection"
          ./deletion_script $con_name
          sleep 2
          ./parsing_commands $con_name $num $timestamp

          # break inner loop so outer while restarts
          break
      fi
  done

  # tiny pause
  sleep 1
done
