#!/bin/bash

if [ $# -ne 4 ]
then
  echo "Usage: ."
fi

num=$(python3 -c "import random; print(random.randint(1,3))")
echo "config num is $num "

# Generate timestamp
timestamp=$(date +%s)   # or use +"%Y%m%d%H%M%S" for readable format

# Combine into the container name
newContainerName="hp-${num}-${timestamp}"
echo "New container name: $newContainerName"

newContainerName=hp-${num}
#making the 1st container'
./new_create start "$num"

num=$(python3 -c "import random; print(random.randint(1,3))")
echo "config num is $num "
#making the 2nd container

num=$(python3 -c "import random; print(random.randint(1,3))")
echo "config num is $num "
#making the 3rd container

num=$(python3 -c "import random; print(random.randint(1,3))")
echo "config num is $num "
#making the 4th container 

num=$(python3 -c "import random; print(random.randint(1,3))")
echo "config num is $num "'


while true
do
./create 



