#!/bin/bash

if [ $# -ne 3 ]
then
  echo "Usage: <container name> <configuration number> <timestamp>"
  exit 1
fi

con_name=$1
config_num=$2
timestamp=$3

mitm_log="/home/aces/Bumblebees/${con_name}_logs/${con_name}_${timestamp}.log"

OUTDIR="/home/aces/Bumblebees/Attacker_Data"
mkdir -p "$OUTDIR"
epoch=$(date +%s)
outfile="${OUTDIR}/${con_name}_${timestamp}.txt"

echo "$con_name" >> "$outfile"
echo "$config_num" >> "$outfile"

attacker_ip=$(sudo cat ${mitm_log} | grep "Attacker connected" | cut -d' ' -f8 | head -1)
echo "$attacker_ip" >> "$outfile"

login_time=$(sudo cat ${mitm_log} | grep "Attacker authenticated" | cut -d' ' -f1-2 | head -1)
echo "$login_time" >> "$outfile"

exit_time=$(sudo cat ${outfile} | head -1 | cut -d' ' -f1-2)
echo "$exit_time" >> "$outfile"

list_commands=$(sudo cat ${mitm_log} | grep "line from read" | cut -d' ' -f9-)

if [ -z "$list_commands" ]; then
  if sudo grep -qF "Noninteractive mode" "$mitm_log"; then
    sudo grep "Noninteractive mode" "$mitm_log" >> "$outfile"
    list_commands=$(sudo sed -n '/^[[:space:]]*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/!p' "$mitm_log")
    num_commands=$(sudo sed -n '/^[[:space:]]*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/!p' "$mitm_log" | wc -l)
    (( num_commands++ )) 
  else
    num_commands=0
  fi
else
  num_commands=$(echo "$list_commands" | wc -l)
fi

echo "${num_commands}" >> "$outfile"

echo "$list_commands" >> "$outfile"
echo

s1=$(date -d "1970-01-01 echo $login_time | cut -d' ' -f2" +%s) 
s2=$(date -d "1970-01-01 echo $exit_time | cut -d' ' -f2" +%s) 
diff=$((s2 - s1)) 
minutes=$((diff / 60)) 
seconds=$((diff % 60))

echo "$minutes minutes and $seconds" >> "$outfile"

sudo tail -n +2 "$outfile" > temp && sudo mv temp "$outfile"



