#!/bin/bash

if [ $# -ne 3 ]
then
  echo "Usage: <container name> <configuration number> <timestamp>"
  exit 1
fi

con_name=$1
config_num=$2
timestamp=$3

mitm_log="/home/aces/Bumblebees/${con_name}_logs/${con_name}_${timestamp}.log"

OUTDIR="/home/aces/Bumblebees/Attacker_Data"
mkdir -p "$OUTDIR"
epoch=$(date +%s)
outfile="${OUTDIR}/${con_name}_${timestamp}.txt"

echo "$con_name" >> "$outfile"
echo "$config_num" >> "$outfile"

attacker_ip=$(sudo cat ${mitm_log} | grep "Attacker connected" | cut -d' ' -f8)
echo "$attacker_ip" >> "$outfile"

login_time=$(sudo cat ${mitm_log} | grep "Attacker authenticated" | cut -d' ' -f1-2)
echo "$login_time" >> "$outfile"

exit_time=$(sudo cat ${outfile} | head -1 | cut -d' ' -f1-2)
echo "$exit_time" >> "$outfile"



list_commands=$(sudo cat ${mitm_log} | grep "line from read" | cut -d' ' -f9-)

num_commands=$(echo "$list_commands" | wc -l)

echo "${num_commands}" >> "$outfile"

echo "$list_commands" >> "$outfile"
echo

# Convert to seconds since epoch (same dummy date)
s1=$(date -d "1970-01-01 `echo $login_time | cut -d' ' -f2`" +%s)
s2=$(date -d "1970-01-01 `echo $exit_time | cut -d' ' -f2`" +%s)

diff=$((s2 - s1))
minutes=$((diff / 60))
seconds=$((diff % 60))

echo "$minutes minutes and $seconds seconds" >> "$outfile"

sudo tail -n +2 "$outfile" > temp && sudo mv temp "$outfile"



