#!/bin/bash

# Get random number 1-3 from Python

num=$(python3 -c "import random; print(random.randint(1,3))")

# Name of container



# Use if/elif/else
if [ "$num" -eq 1 ]; then
    ./creation 1
elif [ "$num" -eq 2 ]; then
    ./creation 2
else
    ./creation 3
fi
