#!/bin/bash

# Get random number 1-3 from Python
num=$(python3 -c "import random; print(random.randint(1,3))")

echo "Random number is: $num"

# Use if/elif/else
if [ "$num" -eq 1 ]; then
    echo "config is Office of the Registar"
elif [ "$num" -eq 2 ]; then
    echo "config is Office of Student Financial Aid"
else
    echo "config is Department of Computer Science"
fi
